log_level: fine
coloured_console: true
rename_level_cost: 5
particle_effects: 2
debug_level: 0
save_interval: 30
enable:
  angelicblock: true
  blockupdatedetector: true
  elevator: true
  paintcan: true
  redstoneclock: true
  soundmuffler: true
  trashcan: true
  advancedmoisturechecker: true
  bagofholding: true
  buildersmultitool: true
  diamondcombinehoe: true
  goldcombinehoe: true
  ironcombinehoe: true
  woodcombinehoe: true
  moisturechecker: true
  paintbrush: true
  paintroller: true
  tapemeasure: true
  wateringcan: true
