name: URL Validator

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    name: URL Checker
    runs-on: ubuntu-latest

    steps:
    - name: URL-checker
      uses: SuperKogito/URLs-checker@0.2.1
      with:
        git_path: https://github.com/Slimefun/SensibleToolbox
        file_types: .md,.java,.yml
        print_all: False
        retry_count: 2
        ## These URLs will always be correct, even if their services may be offline right now
        white_listed_patterns: https://pastebin.com/
